# Generated by Django 5.2.5 on 2026-06-22 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=20, verbose_name='Plaka')),
                ('motor_no', models.CharField(max_length=50, verbose_name='Motor No')),
                ('chassis_no', models.CharField(max_length=50, verbose_name='Şasi No')),
                ('brand_model', models.CharField(max_length=100, verbose_name='Marka ve Model')),
                ('vehicle_type', models.CharField(max_length=50, verbose_name='Tipi')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Bakım Tarihi')),
                ('km', models.IntegerField(verbose_name='Bakım Kilometresi')),
                ('next_km', models.IntegerField(verbose_name='Gelecek Bakım Kilometresi')),
                ('description', models.TextField(verbose_name='Yapılan İşlemler / Açıklama')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='records.vehicle', verbose_name='Araç')),
            ],
        ),
    ]
