# Generated by Django 5.2.5 on 2026-07-05 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_vehicle_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='chassis_no',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='motor_no',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_type',
        ),
    ]
